server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: author
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**, 
        - id: subscription
          uri: http://localhost:8083
          predicates:
            - Path=/subscribers/**, /subscribes/**, /subscribeViews/**
        - id: writing
          uri: http://localhost:8084
          predicates:
            - Path=/writings/**, 
        - id: point
          uri: http://localhost:8085
          predicates:
            - Path=/point/**, 
        - id: review
          uri: http://localhost:8086
          predicates:
            - Path=/bookServices/**, 
        - id: ai
          uri: http://localhost:8087
          predicates:
            - Path=/ais/**, 
        - id: book
          uri: http://localhost:8088
          predicates:
            - Path=/books/**, 
        - id: dashboard
          uri: http://localhost:8089
          predicates:
            - Path=/dashboard/**, /mypages/**
        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/
            - Path=/index.html
            - Path=/static/**
            - Path=/assets/**
            - Path=/favicon.ico
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://author:8080
          predicates:
            - Path=/authors/**, 
        - id: subscription
          uri: http://subscription:8080
          predicates:
            - Path=/subscribers/**, /subscribes/**, 
        - id: writing
          uri: http://writing:8080
          predicates:
            - Path=/writings/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/ν¬μΈνΈ/**, 
        - id: review
          uri: http://review:8080
          predicates:
            - Path=/bookServices/**, 
        - id: ai
          uri: http://ai:8080
          predicates:
            - Path=/ais/**, 
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/books/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=dashboard/**, /mypages/**
        - id: frontend
          uri: http://frontend:3000
          predicates:
            - Path=/
            - Path=/index.html
            - Path=/static/**
            - Path=/assets/**
            - Path=/favicon.ico
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
